### ISSUE TITLE
Cannot receive data

### ISSUE THREAD

**Issue by mburakbozbey** [richstokes/Forza-data-tools#1]
Hi,

I'm trying to run the code on Windows 10 with Forza Horizon 4. I set game settings for data output as same as what the script listens. I'm not familiar with golang but I installed it for Windows 64bit and added it to path. The only change that I did is I renamed "fdt" to "fdt.file" due to the an error. After that, the program prints  waiting for Forza data but receives nothing. Any suggestions? I suspect that the game fails to send any data

**Comment by richstokes** [comment]
Assuming windows firewall isnt blocking it, I would try restarting the game after enabling UDP data out. I've seen Forza sometimes not send data for some reason, but restarting the game fixes it.

**Comment by mikeonator** [comment]
@mburakbozbey @richstokes 
From messing around with Forza's data out function, I recently learned that Windows actually blocks Windows Store applications from communicating with localhost, so you have to find a loop back program like I did to get by this.

**Comment by jonbrandon** [comment]
It looks like for Forza Horizon 4 you can get around this by opening a Command Prompt with Administrator privileges and running:

CheckNetIsolation.exe LoopbackExempt -a -n=Microsoft.SunriseBaseGame_8wekyb3d8bbwe

Likewise, to solve this for Forza Motorsport 7 run the following instead:

CheckNetIsolation.exe LoopbackExempt -a -n=microsoft.apollobasegame_8wekyb3d8bbwe

**Comment by atsushiienaka** [comment]
Hi @richstokes Thank you so much for sharing this project. But I can't receive the data. 
Where can I find the data?
It would be really helpful if you could give me any advice...

The steps I took are below:

- Using Forza Horizon 4 & Trying to use this app on Mac (OS version: Catalina 10.15.6)
- Since my terminal said the port 9999 is already in use (I don't know where), I changed the port number in "main.go" to something else, and set it in the data out port in the game's settings.
- Built the app and typed the command like `./fdt -z -j -c log.csv` in terminal.
- It returns like this below and showing nothing in the csv
`14:02:43.348602 Started Forza Data Tools
14:02:43.349029 Forza Horizon mode selected
14:02:43.349571 Processing FH4_packetformat.dat...
14:02:43.349671 Proccessed 86 Telemetry types OK!
14:02:43.349681 Logging data to log.csv
14:02:43.350225 JSON Telemetry Server started at http://localhost:8080
14:02:43.350535 Forza data out server listening on 192.168.178.25:8989, waiting for Forza data...`

**Comment by richstokes** [comment]
Assuming your game is set to use `192.168.178.25:8989` as the data out address, that should be all you need to do.

I have seen a bug in Forza where you sometimes need to completely quit and restart the game before it sends the data correctly when you change the IP/port.

**Comment by thumpnail** [comment]
I would say that restarting my pc fixed this issue for now. Can read the Telemetry data with the data tools.

**Comment by atsushiienaka** [comment]
By turning Firewall off, it worked. Thanks for your advices above.
